spring.datasource.url=jdbc:mysql://localhost:3306/petshop?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Daniellanoi1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=bWV1c2VncmVkb3N1cGVyc2VndXJvcGFyYW9wZXRzaG9wMjAyNg==
jwt.expiration=86400000

